server:
  port: 5000

spring:
  application:
    name: similar-products
  main:
    banner-mode: "off"

app:
  upstream:
    base-url: http://localhost:3001
    timeout-ms: 2000
  cache:
    similar-ids-ttl-seconds: 120
    product-detail-ttl-seconds: 120
    maximum-size: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.itx.similarproducts: INFO
